blog/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^$', views.event_list),
    url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>[0-9]+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^drafts/$', views.post_draft_list, name='post_draft_list'),
    url(r'^post/(?P<pk>[0-9]+)/publish/$', views.post_publish, name='post_publish'),
    url(r'^post/(?P<pk>[0-9]+)/remove/$', views.post_remove, name='post_remove'),
    url(r'^post/(?P<pk>[0-9]+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>[0-9]+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>[0-9]+)/remove/$', views.comment_remove, name='comment_remove'),
    url(r'^events/$', views.event_list),
    url(r'^events/new/$', views.event_new, name='event_new'),
    url(r'^events/(?P<pk>[0-9]+)/$', views.event_detail),

]

mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
    url(r'', include('blog.urls')),
    

]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Los diferentes estados de una tarea
STATUS = (
    ('S', 'Sin asignar'),
    ('P','Pendiente'),
    ('R', 'Realizada')
)

class Post(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)  
    text = models.TextField()
    created_date = models.DateTimeField(
	default=timezone.now)
    published_date = models.DateTimeField(
	blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()
    
    def approved_comments(self):
        return self.comments.filter(approved_comment=True)

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey('blog.Post', related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

class Event(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    description = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    curso = models.ForeignKey('blog.Curso',related_name='eventcurso', null=True,blank=True )
    when = models.DateTimeField(null=True)
    where = models.CharField(max_length=2000, null=True)

    def pending_tasks(self):
        return self.tasks.filter(status='S')

    def __str__(self):
        return self.title


class Task(models.Model):
    event = models.ForeignKey('blog.Event', related_name='tasks')
    title = models.CharField(max_length=200)
    description = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=1, choices=STATUS, default='S')
    budget = models.FloatField(default=0.0)
    owner = models.ForeignKey('blog.Parent', related_name='parentasks', null=True, blank=True)

    def __str__(self):
        return self.title


class Pupil(models.Model):
    GENDER = (
        ('M','Masculino'),
        ('F', 'Femenino')
        )
    name = models.CharField(max_length=40)
    birthday = models.DateField()
    gender = models.CharField(max_length=1, choices=GENDER, default='M')
    eventsassisted = models.ManyToManyField('blog.Event',related_name='pupilassists', null=True, blank=True)
    curso = models.ForeignKey('blog.Curso',related_name='pupilstudies', null=True,blank=True )

    def __str__(self):
        return self.name


class Parent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=40)
    pupil = models.ManyToManyField('blog.Pupil', related_name='parents', null=True)
    eventsorganized = models.ManyToManyField('blog.Event',related_name='parentorganizes', null=True, blank=True)
    eventsassisted = models.ManyToManyField('blog.Event',related_name='parentassists', null=True, blank=True)

    def __str__(self):
        return self.name


class Curso(models.Model):

    name = models.CharField(max_length=50)
    description = models.TextField()

    def __str__(self):
        return self.name

blog/forms.py
from django import forms

from .models import Post, Comment, Event

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('author', 'text',)

class EventForm(forms.ModelForm):

    class Meta:
        model = Event
        fields = ('title', 'description', 'curso', 'where', 'when')

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Post, Comment, Event, Parent, Pupil, Task, Curso
from .forms import PostForm, CommentForm, EventForm
from django.contrib.auth.decorators import login_required

def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'blog/post_list.html', {'posts': posts})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})

@login_required
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('blog.views.post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})

@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('blog.views.post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})

@login_required
def post_draft_list(request):
    posts = Post.objects.filter(published_date__isnull=True).order_by('created_date')
    return render(request, 'blog/post_draft_list.html', {'posts': posts})

@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('blog.views.post_detail', pk=pk)

@login_required
def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('blog.views.post_list')

def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('blog.views.post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/add_comment_to_post.html', {'form': form})

@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('blog.views.post_detail', pk=comment.post.pk)

@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('blog.views.post_detail', pk=post_pk)

@login_required
def event_list(request):
    childs = Pupil.objects.filter(parents__user=request.user)
    events = []
    for child in childs:
        curso = Curso.objects.filter(pupilstudies=child)
        eventsOfCurso = Event.objects.filter(curso=curso)
        events.extend(eventsOfCurso)
    #events = Event.objects.filter(created_date__lte=timezone.now()).order_by('created_date')
    print(events)
    return render(request, 'blog/event_list.html', {'events': events})

@login_required
def event_new(request):
    if request.method == "POST":
        form = EventForm(request.POST)
        if form.is_valid():
            event = form.save(commit=False)
            event.author = request.user
            event.save()
            return redirect('blog.views.event_detail', pk=event.pk)
    else:
        form = EventForm()
    return render(request, 'blog/event_edit.html', {'form': form})

@login_required
def event_detail(request, pk):
    event = get_object_or_404(Event, pk=pk)
    organizers = event.parentorganizes.all()
    assistants = event.pupilassists.all()

    return render(request, 'blog/event_detail.html', {'event': event, 'organizers': organizers, 'assistants':assistants})

blog/templates/blog/add_comment_to_post.html
{% extends "blog/base.html" %}

{% block content %}
    <h1>New comment</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
{% endblock %}

blog/templates/blog/asist_list.html
{% extends "blog/base.html" %}
    {% block content %}
        {% for asist in asists %}
            <div class="post">
                <div class="date">
                    {{ asist.event }}

                </div>

                <p>{{ asist.pupil|linebreaks }}</p>
                <p>Acompañantes {{asist.childnumber }}</p>
                <p>Total {{ total }}</p>
            </div>
        {% endfor %}
    {% endblock content %}

blog/templates/blog/base.html
{% load staticfiles %}
    <html>
        <head>
            <title>Janpara blog</title>
            <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
            <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
            <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
            <link rel="stylesheet" href="{% static "css/blog.css" %}">
        </head>
        <body>
        <div class="page-header">
            {% if user.is_authenticated %}
                <a href="{% url "post_new" %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
                <a href="{% url "event_new" %}" class="top-menu">nuevo evento</a>
                <a href="{% url "post_draft_list" %}" class="top-menu"><span class="glyphicon glyphicon-edit"></span></a>
                <p class="top-menu">Hello {{ user.username }}<small>(<a href="{% url "django.contrib.auth.views.logout" %}">Log out</a>)</small></p>
            {% else %}
                <a href="{% url "django.contrib.auth.views.login" %}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
            {% endif %}
        <h1><a href="{% url "blog.views.event_list" %}">Janpara Blog</a></h1>
        </div>
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                {% block content %}
                {% endblock %}
                </div>
            </div>
        </div>
    </body>
    </html>

blog/templates/blog/event_detail.html
{% extends "blog/base.html" %}

    {% block content %}
        <div class="post">

                <div class="date">
                    {{ event.created_date }}
                 
                </div>


            <h1>{{ event.title }}</h1>
            <p>{{ event.description|linebreaks }}</p>
            <p>{{ event.where|linebreaks }}</p>
            <p>{{ event.when|linebreaks }}</p>
        </div>
        <hr>

		{% for task in event.tasks.all %}

                         <div class="comment">
                             <div class="date">
                                  {{ task.created_date }}

                             </div>
                             <strong>{{ task.author }}</strong>
                             <p>{{ task.description|linebreaks }}</p>
                             {% if task.status = 'S' %}
                                <p style="color: red">{{ task.get_status_display }}</p>
                             {% else %}
                                <p style="color: blue">{{ task.get_status_display }}</p>
                             {% endif %}
                             <p>Presupuesto :{{ task.budget }}</p>
                        </div>

		{% empty %}
		    <p>No tasks here yet :(</p>
		{% endfor %}

        <h3>ORGANIZAN</h3>
        {% for organizer in organizers %}


                         <div class="comment">

                                  {{ organizer.name }}



                        </div>
		{% empty %}
		    <p>No organizers here yet :(</p>
		{% endfor %}

        <h3>ASISTEN</h3>
        {% for assistant in assistants %}


                         <div class="comment">

                                  {{ assistant.name }}



                        </div>
		{% empty %}
		    <p>No assistants here yet :(</p>
		{% endfor %}

    {% endblock %}

blog/templates/blog/event_edit.html
{% extends "blog/base.html" %}

    {% block content %}
        <h1>Nuevo Evento</h1>
        <form method="POST" class="post-form">{% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-default">Save</button>
        </form>
    {% endblock %}

blog/templates/blog/event_list.html
{% extends "blog/base.html" %}
    {% block content %}
        {% for event in events %}
            <div class="post">
                <div class="date">
                    {{ event.created_date }}

                </div>
                <h1>{{ event.title }}</h1>
                <p>{{ event.description|linebreaks }}</p>
                <a href="{% url 'blog.views.event_detail' pk=event.pk %}">Tareas sin asignar: {{ event.pending_tasks.count }}</a>

            </div>
        {% endfor %}
    {% endblock content %}

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}

    {% block content %}
        <div class="post">
            {% if post.published_date %}
                <div class="date">
                    {{ post.published_date }}
                
            {% else %}
                 <a class="btn btn-default" href="{% url "blog.views.post_publish" pk=post.pk %}">Publish</a>
                 
                </div>
            {% endif %}
            {% if user.is_authenticated %}
                 <a class="btn btn-default" href="{% url "post_edit" pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
                 <a class="btn btn-default" href="{% url "post_remove" pk=post.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
            {% else %}
                 <a href="{% url "django.contrib.auth.views.login" %}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
            {% endif %}
            <h1>{{ post.title }}</h1>
            <p>{{ post.text|linebreaks }}</p>
        </div>
        <hr>
             <a class="btn btn-default" href="{% url "add_comment_to_post" pk=post.pk %}">Add comment</a>
		{% for comment in post.comments.all %}
		    {% if user.is_authenticated or comment.approved_comment %}
                         <div class="comment">
                             <div class="date">
                                  {{ comment.created_date }}
                                  {% if not comment.approved_comment %}
                                       <a class="btn btn-default" href="{% url "comment_remove" pk=comment.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
                                       <a class="btn btn-default" href="{% url "comment_approve" pk=comment.pk %}"><span class="glyphicon glyphicon-ok"></span></a>
                                  {% endif %}
                             </div>
                             <strong>{{ comment.author }}</strong>
                             <p>{{ comment.text|linebreaks }}</p>
                        </div>
                   {% endif %}
		{% empty %}
		    <p>No comments here yet :(</p>
		{% endfor %}
    {% endblock %}

blog/templates/blog/post_draft_list.html
{% extends "blog/base.html" %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <p class="date">created: {{ post.created_date|date:"d-m-Y" }}</p>
            <h1><a href="{% url "blog.views.post_detail" pk=post.pk %}">{{ post.title }}</a></h1>
            <p>{{ post.text|truncatechars:200 }}</p>
        </div>
    {% endfor %}
{% endblock %}

blog/templates/blog/post_edit.html
{% extends "blog/base.html" %}

    {% block content %}
        <h1>New post</h1>
        <form method="POST" class="post-form">{% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-default">Save</button>
        </form>
    {% endblock %}

blog/templates/blog/post_list.html
{% extends "blog/base.html" %}
    {% block content %}
        {% for post in posts %}
            <div class="post">
                <div class="date">
                    {{ post.published_date }}

                </div>
                <h1><a href="{% url "blog.views.post_detail" pk=post.pk %}">{{ post.title }}</a></h1>
                <p>{{ post.text|linebreaks }}</p>
                <a href="{% url "blog.views.post_detail" pk=post.pk %}">Comments: {{ post.approved_comments.count }}</a>
            </div>
        {% endfor %}
    {% endblock content %}  